version: '3.6'

services:
  db:
    image: mysql:8
    container_name: mysql_test_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    networks:
      - custom_network


networks:
  custom_network:
    name: custom_network
